AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  ConfigEvalFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.6
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSConfigRulesExecutionRole
        - AmazonEC2ReadOnlyAccess

