AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  ConfigEvalFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.6
      Policies:
        - AWSLambdaBasicExecutionRole   # Managed policy
        - Version: '2012-10-17'         # AWS Config put policy
          Statement:
            - Effect: Allow
              Action:
                - config:Put*
              Resource: '*'
        - Version: '2012-10-17'         # EC2 describe policy
          Statement:
            - Effect: Allow
              Action:
                - ec2:Describe*
              Resource: '*'
